### ISSUE TITLE
Cannot move over wall when vaulting is disabled, and token elevation is equal to the wall height.

### ISSUE THREAD

**Issue by cs96and** [theripper93/wall-height#12]
1. Disable vaulting.
2. Create a wall with a height of 20ft. 
3. Set a token to an elevation of 20ft
4. Try to move the token over the wall using the cursor keys.  The token will not be able to move past the wall.
5. Set the token elevation to 20.01.  The token can now move over the wall.

**Comment by theripper93** [comment]
This is intentional as you can read from the change log, the behavior has been changed from the previous version of wall height, if your maps relied on exact numbers there is a macro to -1 all the walls in the map

**Comment by cs96and** [comment]
I looked at the changelog and can't see anything related to being at the same height as the top of a wall.

I'm not migrating, this is a new module install for me.  In my head it makes sense that you can walk over a wall with top height 10ft, if my feet are at 10ft.

**Comment by cs96and** [comment]
The breaking change says...
> The Top of walls is now included in vision blocking calculations

I'm not talking about vision calculation, I'm talking about moving.

**Comment by theripper93** [comment]
I’ll correct it it make it more clear, but it blocks both

**Comment by cs96and** [comment]
But the vision is not being blocked in my case.  I can see over the wall, but can't move over it.  That seems incorrect to me.

**Comment by theripper93** [comment]
That’s because of token height , check that section of the readme, if you want you can customize it such that you have the old behavior (eg younset the global height to 1 and disable the auto height in the module setting )

**Comment by cs96and** [comment]
The token height should have no effect.  My token is at elevation 20ft.  That means its feet are 20ft off the ground and can therefore step over a 20ft wall,  The height of my token is irrelevant at that point.

**Comment by cs96and** [comment]
Basically, you just need to change a > to a >= somewhere in your code.

**Comment by theripper93** [comment]
> 

No it can’t, a 20 ft top wall will block movement of a 20 elevation token unless you enable vaulting

**Comment by cs96and** [comment]
Yes but my point is that it shouldn't.  It's no different to walking on the floor, which has elevation zero, and the token would also have elevation zero.

**Comment by theripper93** [comment]
It was decider to make not work like that for some new features to play nice together we can agree to disagree but it’s not gonna change
