### ISSUE TITLE
Error: k is not defined

### ISSUE THREAD

**Issue by AaronWebster** [theripper93/wall-height#17]
Affects Wall Height 4.4 and Better Roofs 1.6.

![Screenshot from 2022-07-11 09-12-56](https://user-images.githubusercontent.com/3766083/178309676-c0a7bbb2-8fa7-471d-9756-d6ed0a4e34d4.png)

**Comment by theripper93** [comment]
Hello! It seems you haven't read the Before Posting an issue as indicated at the top of the Repository Readme (https://github.com/theripper93/Levels/blob/v9/ISSUES.md) The Issue has been closed.

If you are reporting a bug, feel free to follow the steps here (https://theripper93.com/#/faq/issues) and reopen the issue with all the relevant information.

**Comment by AaronWebster** [comment]
Updated issue as per template.

**Comment by theripper93** [comment]
Hello! It seems you haven't read the Before Posting an issue as indicated at the top of the Repository Readme (https://github.com/theripper93/Levels/blob/v9/ISSUES.md) The Issue has been closed.
