### ISSUE TITLE
Suggestion : mark non visible aeras that are hiden from an wall i can oversee in an way ...

### ISSUE THREAD

**Issue by R0TEAM** [theripper93/wall-height#18]
Hope i can explain it (english not my first language ..)
If you are on an higher ground (elevated) and in front of you it is an big stone .. from the highert ground i can see over the stone ...
So on the canvas the stone DONT block my LOS - this is right behavor ...
But .. if an Token behind the stone on normal hight ground - it is maybe not shown as it is blocked from the hight of the stone to see ...
Even this is correct and nice ...
But .... the player cant see that here his sight is limited .... for him it looks it can see all here and it is nothing here ...
This aera should be marked .. with an special pattern ... with an fog of other color ... anything ...
That the player know ...
He can see over the stone, but the stone block LOS of the ground in this aera, and here can be things that are not visible for the player ...

Regards

**Comment by theripper93** [comment]
Sorry but this is not a planned feature as it would be too disruptive to core foundry .
