### ISSUE TITLE
Feature Request: Option to separate token scale from token size on seeing over walls/waulting

### ISSUE THREAD

**Issue by Malkyn99** [theripper93/wall-height#25]
Title. It's possible to create tokens that exceed the border of their space by upping the scale, and this sometimes works to create cool effects. Unfortunately, since the module multiples token size by grid size, this results in tokens that calculate height as though they were 1.5 times the size sometimes. If there were a way to make it so the token's programmed Size category (for systems that have them) is decoupled from the scale option, that would be super appreciated. If there is already a way to do so in the options and I missed it, I'm sorry. I toyed with it and could not produce anything in line with this request.

**Comment by theripper93** [comment]
Hello! It seems you haven't read the Before Posting an issue as indicated at the top of the Repository Readme (https://github.com/theripper93/Levels/blob/v9/ISSUES.md) The Issue has been closed.

If you are reporting a bug, feel free to follow the steps here (https://theripper93.com/#/faq/issues) and reopen the issue with all the relevant information.
