### ISSUE TITLE
Can't edit the setting of walls

### ISSUE THREAD

**Issue by Exkilter** [theripper93/wall-height#26]
When Wall height is activated I can't double click on walls and edit their settings.

**Comment by theripper93** [comment]
Hello! It seems you haven't read the [Before Posting an issue](https://theripper93.com/info/issues) as indicated at the top of the Repository Readme The Issue has been closed.

If you are reporting a bug, feel free to follow the steps here (https://theripper93.com/info/issues) and reopen the issue with all the relevant information.
