### ISSUE TITLE
[Feature Request] Add toggle for token scale for auto height calculation in settings

### ISSUE THREAD

**Issue by Sebmaster777** [theripper93/wall-height#28]
This is so that if you have a token with a bigger scale than 1, you can keep the normal calculation without multiplying the height by the scale

EDIT: on second thought, perhaps have it as a toggle in the token configuration, as you might want to keep it for small tokens (such as tiny creatures) but turn it off for big creatures.

**Comment by theripper93** [comment]
Hello! It seems you haven't read the Before Posting an issue as indicated at the top of the Repository Readme The Issue has been closed.

If you are reporting a bug, feel free to follow the steps here (https://theripper93.com/info/issues) and reopen the issue with all the relevant information.
