### ISSUE TITLE
After installing the wall with the adjusted height, all the tool buttons stop working.

### ISSUE THREAD

**Issue by Wrasal** [theripper93/wall-height#29]
I tested it on a new world with the Swade system. With the appearance of a wall with a customized height on the stage, the side menu of the tools stops responding. After some clicks, the tool changes, it does not work properly, and the walls continue to be displayed on the screen.

**Comment by theripper93** [comment]
Hello! It seems you haven't read the [Before Posting an issue](https://theripper93.com/info/issues) as indicated at the top of the Repository Readme The Issue has been closed.

If you are reporting a bug, feel free to follow the steps here (https://theripper93.com/info/issues) and reopen the issue with all the relevant information.
