### ISSUE TITLE
Walls height didn't changed with active Walled Templates and/or Elevation Ruler

### ISSUE THREAD

**Issue by ArtemBogdanov** [theripper93/wall-height#31]
**I have disabled all other modules:** True
**Module(s)** Wall Height
**Conflicting Module(s)** Walled Templates 0.8.0, Elevation Ruler 0.9.12
**Foundry and System version** Foundry 12.330, DnDe5 3.3.1
**OS, Hosting, Browser (if applicable)** Windows 10, self-hosting, Chrome
**Short description of bug** Walls height didn't changed
**Simple steps to reproduce the bug**

1) Set up more than one wall.
2) Select the walls that have been set up.
3) Change the height of the selected walls. It will change.
4) Try repeating the previous step. The height will not change.

Walled Templates and Elevation Ruler separately and together lead to irregular behavior.

**Screenshots and/or Console Errors**
[with_walled_teplates.webm](https://github.com/user-attachments/assets/e0017e18-8514-4ae6-adb0-c36cda91bce9)
[logs_with_walled_teplates.log](https://github.com/user-attachments/files/16482372/logs_with_walled_teplates.log)
[with_elevation_ruler.webm](https://github.com/user-attachments/assets/8bc376bb-6367-4933-93b6-4109d4df157e)
[logs_with_elevation_ruler.log](https://github.com/user-attachments/files/16482373/logs_with_elevation_ruler.log)

**Comment by theripper93** [comment]
I'm unclear what this has to do with wallheight, is the bug report that other modules are breaking multiple wall updates?

**Comment by theripper93** [comment]
This is an issue with the other modules breaking the wall heigth inputs, please report this to the modules in question.
