### ISSUE TITLE
Bad performance with PF2E Auras

### ISSUE THREAD

**Issue by Matrayo** [theripper93/wall-height#33]
When this module is enabled, the system performance becomes extremely poor if auras are active in the PF2E system. This has been replicated with animations turned on or off.

**Comment by theripper93** [comment]
Hello! It seems you haven't read the [Before Posting an issue](https://theripper93.com/info/issues) as indicated at the top of the Repository Readme The Issue has been closed.

If you are reporting a bug, feel free to follow the steps here (https://theripper93.com/info/issues) and reopen the issue with all the relevant information.
